apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hale-platform-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: hale.docker 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx 
            port:
              number: 8080 
