---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-wordpress 
  labels:
    app: wordpress-c
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

