apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - svc-mysql.yaml
  - svc-wordpress.yaml
  # svc-nginx.yaml // bc CloudPlatforms doesn't allow running an NGINX loadbalancer
  - pvc-mysql.yaml
  - pvc-wordpress.yaml
  - deploy-mysql.yaml
  - deploy-wordpress.yaml
  - deploy-nginx.yaml
