{{- if .Values.alertSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata: 
  name: alert-secrets-{{ .Release.Revision }} 
type: Opaque
stringData:
  alert_slack_webhook_url: {{ .Values.alertSecrets.slackWebhookUrl }}
{{- end }}
