apiVersion: v1
kind: ConfigMap
metadata:
  name: wpconfig-{{ .Release.Revision }}
data:
  WP_ENVIRONMENT_TYPE: {{ .Values.configmap.wpenvtype }}
  SERVER_NAME: {{ .Values.domain }}
  ENV_TYPE: {{ .Values.configmap.envtype }}
