apiVersion: v1
kind: ConfigMap
metadata:
  name: hale-wp-config-{{ .Release.Revision }}
data:
  WP_ENVIRONMENT_TYPE: {{ .Values.configmap.envtype }}
  SERVER_NAME: {{ .Values.domain }}
  ENV_TYPE: {{ .Values.configmap.envtype }}
  S3_UPLOADS_USE_INSTANCE_PROFILE: {{ .Values.configmap.s3useprofile | quote }}
  PHP_DSN: {{ .Values.configmap.sentrydns }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hale-nginx-config-{{ .Release.Revision }}
data:
  FIREWALL_ENABLED: {{ .Values.configmap.firewall.enabled | quote }}
  FIREWALL_BLOCK_THRESHOLD: {{ .Values.configmap.firewall.blockthreshold | quote }}
  FIREWALL_SCORE_TTL: {{ .Values.configmap.firewall.scorettl | quote }}
