apiVersion: v1
kind: ConfigMap
metadata:
  name: wpconfig-{{ .Release.Revision }}
data:
  WP_ENVIRONMENT_TYPE: {{ .Values.configmap.envtype }}
  SERVER_NAME: {{ .Values.domain }}
  ENV_TYPE: {{ .Values.configmap.envtype }}
  {{- if eq .Values.configmap.envtype "staging" }}
  WP_DEBUG: "false"
  {{ else if eq .Values.configmap.envtype "dev" }}
  WP_DEBUG: "true"
  {{ else if eq .Values.configmap.envtype "demo" }}
  WP_DEBUG_FILE: "true"
  {{ else }}
  WP_DEBUG: "false"
  {{- end }}