apiVersion: v1
kind: ConfigMap
metadata:
  name: hale-wp-config-{{ .Release.Revision }}
data:
  WP_ENVIRONMENT_TYPE: {{ .Values.configmap.envtype }}
  SERVER_NAME: {{ .Values.domain }}
  ENV_TYPE: {{ .Values.configmap.envtype }}
  S3_UPLOADS_USE_INSTANCE_PROFILE: "true"
  PHP_DSN: {{ .Values.configmap.sentrydns }}
