apiVersion: v1
kind: ConfigMap
metadata:
  name: wpconfig-{{ .Release.Revision }}
data:
  WP_ENVIRONMENT_TYPE: {{ .Values.configmap.envtype }}
  SERVER_NAME: {{ .Values.domain }}
  ENV_TYPE: {{ .Values.configmap.envtype }}
  #S3_UPLOADS_USE_INSTANCE_PROFILE: {{ .Values.configmap.s3useprofile }}
  #{{- if eq .Values.configmap.envtype "staging" }}
  # WP_DEBUG: "false"
  # {{ else if eq .Values.configmap.envtype "dev" }}
  # WP_DEBUG: "true"
  # {{ else if eq .Values.configmap.envtype "demo" }}
  # WORDPRESS_DEBUG: "true"
  # {{ else }}
  # WP_DEBUG: "false"
  # {{- end }}