apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: hale-platform-{{ .Values.configmap.envtype }}
  labels:
    app: wordpress
spec:
  {{- if eq .Values.configmap.envtype "staging" }}
  replicas: {{ .Values.wp.image.replicaCount.staging }}
  {{ else if eq .Values.configmap.envtype "dev" }}
  replicas: {{ .Values.wp.image.replicaCount.dev }}
  {{ else if eq .Values.configmap.envtype "demo" }}
  replicas: {{ .Values.wp.image.replicaCount.demo }}
  {{ else }}
  replicas: {{ .Values.wp.image.replicaCount.prod }}
  {{- end }}
  selector:
    matchLabels:
      app: wordpress
      tier: frontend-c
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend-c
    spec:
      terminationGracePeriodSeconds: 20
      serviceAccountName: hale-platform-{{ .Values.configmap.envtype }}-service
      containers:
        - image: {{ .Values.wp.image.repository }}
          imagePullPolicy: {{ .Values.wp.image.imagePullPolicy }}
          name: wordpress
          env:
            - name: PHP_INI_SCAN_DIR
              value: :/usr/local/etc/php/conf.custom
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: wordpress-volume-file-mount
              mountPath: /var/www/html
            - name: hale-php-config
              mountPath: /usr/local/etc/php/conf.custom
          envFrom:
            - configMapRef:
                name: hale-wp-config-{{ .Release.Revision }}
            - secretRef:
                name: hale-wp-secrets-{{ .Release.Revision }}
          livenessProbe:
            httpGet:
              port: 443
              path: /hale-wpms-2020
              scheme: HTTPS
              host: {{ .Values.domain }}
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  if ! ps aux | grep '[p]hp-fpm: master process' >/dev/null; then
                    exit 1
                  fi
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
        - name: nginx
          image: {{ .Values.nginx.image.repository }}
          imagePullPolicy: {{ .Values.nginx.image.imagePullPolicy }}
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: wordpress-volume-file-mount
              mountPath: /var/www/html
      volumes:
        - name: wordpress-volume-file-mount
          emptyDir: {}
        - name: hale-php-config
          configMap:
            name: hale-php-config-{{ .Release.Revision }}
---