apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: hale-platform-{{ .Values.configmap.envtype }}
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend-c
  replicas: {{ include "wp.replicaCount" . }}
  strategy:
    type: {{ .Values.updateStrategy.type }}
    rollingUpdate:
      maxSurge: {{ .Values.updateStrategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.updateStrategy.rollingUpdate.maxUnavailable }}
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend-c
    spec:
      terminationGracePeriodSeconds: 35
      serviceAccountName: hale-platform-{{ .Values.configmap.envtype }}-service
      containers:
        - name: wordpress
          image: {{ .Values.wp.image.repository }}
          imagePullPolicy: {{ .Values.wp.image.imagePullPolicy }}
          resources:
            limits:
              cpu: {{ index .Values.wp.resources .Values.configmap.envtype "limits" "cpu" }}
              memory: {{ index .Values.wp.resources .Values.configmap.envtype "limits" "memory" }}
            requests:
              cpu: {{ index .Values.wp.resources .Values.configmap.envtype "requests" "cpu" }}
              memory: {{ index .Values.wp.resources .Values.configmap.envtype "requests" "memory" }}
          env:
            - name: PHP_INI_SCAN_DIR
              value: :/usr/local/etc/php/conf.custom
          ports:
            - containerPort: {{ .Values.wp.image.ports.containerPort }}
          volumeMounts:
            - name: wordpress-volume-file-mount
              mountPath: /var/www/html
            - name: hale-php-config
              mountPath: /usr/local/etc/php/conf.custom
          envFrom:
            - configMapRef:
                name: hale-wp-config-{{ .Release.Revision }}
            - secretRef:
                name: hale-wp-secrets-{{ .Release.Revision }}
          {{- if or (eq .Values.configmap.envtype "prod") (eq .Values.configmap.envtype "staging") }}
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  if [ -f /var/www/html/wp-load.php ] && ps aux | grep -q "[p]hp-fpm"
                  then
                    exit 0
                  else
                    exit 1
                  fi
            initialDelaySeconds: 30
            periodSeconds: 3
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
        - name: nginx
          image: {{ .Values.nginx.image.repository }}
          imagePullPolicy: {{ .Values.nginx.image.imagePullPolicy }}
          resources:
            limits:
              cpu: {{ index .Values.nginx.resources .Values.configmap.envtype "limits" "cpu" }}
              memory: {{ index .Values.nginx.resources .Values.configmap.envtype "limits" "memory" }}
            requests:
              cpu: {{ index .Values.nginx.resources .Values.configmap.envtype "requests" "cpu" }}
              memory: {{ index .Values.nginx.resources .Values.configmap.envtype "requests" "memory" }}
          ports:
            - containerPort: {{ .Values.nginx.image.ports.containerPort }}
          volumeMounts:
            - name: wordpress-volume-file-mount
              mountPath: /var/www/html
          {{- if or (eq .Values.configmap.envtype "prod") (eq .Values.configmap.envtype "staging") }}
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  if curl --silent --fail http://localhost:8080 >/dev/null; then
                    exit 0
                  else
                    exit 1
                  fi
            initialDelaySeconds: 35
            periodSeconds: 5
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: wordpress-volume-file-mount
          emptyDir: {}
        - name: hale-php-config
          configMap:
            name: hale-php-config-{{ .Release.Revision }}
