---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: {{ .Values.nginx.image.repository }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
            - containerPort: 443
---
{{- if .Values.mariadb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
      tier: frontend-c
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
        tier: frontend-c
    spec:
      containers:
      - name: mysql  
        image: mariadb:10.7.1-focal
        envFrom:
          - configMapRef:
              name: wpconfig
        ports:
          - containerPort: 3306
            name: mysql
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/li/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: wordpress
      tier: frontend-c
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend-c
    spec:
      containers:
        - image: {{ .Values.image.repository }}
          imagePullPolicy: IfNotPresent
          name: wordpress
          ports:
            - containerPort: 8080
              name: wordpress
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
          envFrom:
            - configMapRef:
                name: wpconfig
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wp-pvc-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  wp-pvc-claim
  labels:
     app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp2 
