{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hale-platform-hpa
  namespace: hale-platform-{{ .Values.configmap.envtype }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wordpress
  {{ include "replicaSettings" . }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          targetAverageUtilization: {{ .Values.autoscaling.targetCPU }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          targetAverageUtilization: {{ .Values.autoscaling.targetMemory }}
{{- end }}
