{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hale-platform-hpa
  namespace: hale-platform-{{ .Values.configmap.envtype }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wordpress
  {{- if eq .Values.configmap.envtype "prod" }}
  minReplicas: 4
  maxReplicas: 5
  {{- else if eq .Values.configmap.envtype "staging" }}
  minReplicas: 2
  maxReplicas: 3
  {{- else if eq .Values.configmap.envtype "demo" }}
  minReplicas: 2
  maxReplicas: 3
  {{- else }}
  minReplicas: 1
  maxReplicas: 1
  {{- end }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 95
{{- end }}
