{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hale-platform-ingress
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: {{ .Values.ingress.metadata.annotations.setidentifier }}
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
        SecRuleEngine On
        SecDefaultAction "phase:2,pass,log,tag:github_team=hale-platform"
        SecRuleRemoveById 949110
spec:
  ingressClassName: modsec
  tls:
  - hosts:
    - {{ .Values.domain }}
    {{- if eq .Values.configmap.envtype "prod" }}
  - hosts:
    - magistrates.judiciary.uk
    secretName: magistrates-cert
  - hosts:
    - victimscommissioner.org.uk
    secretName: victimscommissioner-cert
  - hosts:
    - www.victimscommissioner.org.uk
    secretName: victimscommissioner-www-cert
  - hosts:
    - publicdefenderservice.org.uk
    secretName: publicdefenderservice-cert
  - hosts:
    - www.publicdefenderservice.org.uk
    secretName: publicdefenderservice-www-cert
  - hosts:
    - ccrc.gov.uk
    secretName: ccrc-cert
  - hosts:
    - www.ccrc.gov.uk
    secretName: ccrc-www-cert
  - hosts:
    - icrir.independent-inquiry.uk
    secretName: icrir-cert
  - hosts:
    - imb.org.uk
    secretName: imb-cert
  - hosts:
    - www.imb.org.uk
    secretName: imb-www-cert
  - hosts:
    - brookhouseinquiry.org.uk
    secretName: brookhouse-cert
  - hosts:
    - www.brookhouseinquiry.org.uk
    secretName: brookhouse-www-cert
    {{- end }}
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: wordpress
            port:
              number: 8080
  {{- if eq .Values.configmap.envtype "prod" }}
  - host: magistrates.judiciary.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: wordpress
            port:
              number: 8080
  - host: victimscommissioner.org.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: wordpress
            port:
              number: 8080
  - host: www.victimscommissioner.org.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: wordpress
            port:
              number: 8080
  - host: publicdefenderservice.org.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: wordpress
            port:
              number: 8080
  - host: www.publicdefenderservice.org.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: wordpress
            port:
              number: 8080
  - host: ccrc.gov.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: wordpress
            port:
              number: 8080
  - host: www.ccrc.gov.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: wordpress
            port:
              number: 8080
  - host: icrir.independent-inquiry.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: wordpress
            port:
              number: 8080
  - host: imb.org.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: wordpress
            port:
              number: 8080
  - host: www.imb.org.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: wordpress
            port:
              number: 8080
  - host: brookhouseinquiry.org.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: wordpress
            port:
              number: 8080
  - host: www.brookhouseinquiry.org.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: wordpress
            port:
              number: 8080
   {{- end }}
{{- end }}
