{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hale-platform-ingress
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: {{ .Values.ingress.metadata.annotations.setidentifier }}
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecDefaultAction "phase:2,pass,log,tag:github_team=hale-platform"
      SecRuleRemoveById 949110
    nginx.ingress.kubernetes.io/server-snippet: |
      location = /.well-known/security.txt {
        auth_basic off;
        return 301 https://raw.githubusercontent.com/ministryofjustice/security-guidance/main/contact/vulnerability-disclosure-security.txt;
      }
      if ($host = 'victimscode.org.uk') {
        return 301 https://victimandwitnessinformation.org.uk/your-rights/as-a-victim;
      }
      if ($host = 'cym.victimscode.org.uk') {
        return 301 https://cym.victimandwitnessinformation.org.uk/your-rights/as-a-victim;
      }
spec:
  ingressClassName: modsec
  tls:
  - hosts:
    - {{ .Values.domain }}
{{- if eq .Values.configmap.envtype "prod" }}
  {{- range .Values.ingress.hosts }}
  - hosts:
    - {{ .name }}
    secretName: {{ .certName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: wordpress
                port:
                  number: 8080
  {{- if eq .Values.configmap.envtype "prod" }}
    {{- range .Values.ingress.hosts }}
    - host: {{ .name }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: wordpress
                port:
                  number: 8080
    {{- end }}
  {{- end }}
{{- end }}
