{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hale-platform-ingress
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: {{ .Values.ingress.metadata.annotations.setidentifier }}
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      # Default WAF rules
      SecRuleEngine On
      SecDefaultAction 
        "phase:2,\
        pass,\
        log,\
        tag:github_team=hale-platform,\
        tag:environment=hale-platform-{{ .Values.configmap.envtype }}"
      # Set WAF Config for Authenticated Users
      SecRule REQUEST_HEADERS:Cookie "@contains WAF_CONFIG={{ .Values.secrets.wafconfig }}"
        "id:1001,\
        phase:2,\
        allow,\
        tag:github_team=hale-platform,\
        tag:environment=hale-platform-{{ .Values.configmap.envtype }}-auth,\
        ctl:ruleEngine=DetectionOnly"
    {{- if eq .Values.configmap.envtype "staging" }}
      SecRule REMOTE_ADDR "@ipMatch 80.195.27.199/32" "phase:2,id:200000001,nolog,allow"
    {{- end }}
    nginx.ingress.kubernetes.io/server-snippet: |
      location = /.well-known/security.txt {
        auth_basic off;
        return 301 https://raw.githubusercontent.com/ministryofjustice/security-guidance/main/contact/vulnerability-disclosure-security.txt;
      }
      location /bold {
        if ($host = 'hale-platform-prod.apps.live.cloud-platform.service.justice.gov.uk') {
          return 301 https://bold.websitebuilder.service.justice.gov.uk;
        }
      }
      if ($host = 'victimscode.org.uk') {
        return 301 https://victimandwitnessinformation.org.uk/your-rights/as-a-victim;
      }
      if ($host = 'cym.victimscode.org.uk') {
        return 301 https://cym.victimandwitnessinformation.org.uk/your-rights/as-a-victim;
      }
      if ($host = 'seewhatsontheinside.com') {
        return 301 https://newfuturesnetwork.gov.uk;
      }
      if ($host = 'www.seewhatsontheinside.com') {
        return 301 https://newfuturesnetwork.gov.uk;
      }
      if ($host = 'seewhatsontheinside.co.uk') {
        return 301 https://newfuturesnetwork.gov.uk;
      }
      if ($host = 'www.seewhatsontheinside.co.uk') {
        return 301 https://newfuturesnetwork.gov.uk;
      }
      if ($host = 'advance-into-justice.service.justice.gov.uk') {
        return 301 https://prisonandprobationjobs.gov.uk/roles-at-hmpps/jobs-for-veterans;
      }
      if ($host = 'www.advance-into-justice.service.justice.gov.uk') {
        return 301 https://prisonandprobationjobs.gov.uk/roles-at-hmpps/jobs-for-veterans;
      }
      if ($host = 'iapondeathsincustody.org') {
        return 301 https://iapdeathsincustody.independent.gov.uk;
      }
      if ($host = 'www.iapondeathsincustody.org') {
        return 301 https://iapdeathsincustody.independent.gov.uk;
      }
      if ($host = 'brookhouseinquiry.org.uk') {
        return 301 https://webarchive.nationalarchives.gov.uk/ukgwa/20241002135959/https://brookhouseinquiry.org.uk/;
      }
      if ($host = 'www.brookhouseinquiry.org.uk') {
        return 301 https://webarchive.nationalarchives.gov.uk/ukgwa/20241002135959/https://brookhouseinquiry.org.uk/;
      }
spec:
  ingressClassName: modsec
  tls:
  - hosts:
    - {{ .Values.domain }}
    secretName: websitebuilder-{{ .Values.configmap.envtype }}-cert
{{- if eq .Values.configmap.envtype "prod" }}
  {{- range .Values.ingress.hosts }}
  - hosts:
    - {{ .name }}
    secretName: {{ .certName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: wordpress
                port:
                  number: 8080
  {{- if eq .Values.configmap.envtype "prod" }}
    {{- range .Values.ingress.hosts }}
    - host: {{ .name }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: wordpress
                port:
                  number: 8080
    {{- end }}
  {{- end }}
{{- end }}
