{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hale-platform-ingress
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: {{ .Values.ingress.metadata.annotations.setidentifier }}
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
        SecRuleEngine On
        SecDefaultAction "phase:2,pass,log,tag:github_team=hale-platform"
        SecRuleRemoveById 949110
    nginx.ingress.kubernetes.io/server-snippet: |
        location = /.well-known/security.txt {
        auth_basic off;
        return 301 https://raw.githubusercontent.com/ministryofjustice/security-guidance/main/contact/vulnerability-disclosure-security.txt;
        }
spec:
  ingressClassName: modsec
  tls:
  - hosts:
    - {{ .Values.domain }}
    {{- if eq .Values.configmap.envtype "prod" }}
  - hosts:
    - magistrates.judiciary.uk
    secretName: magistrates-cert
  - hosts:
    - victimscommissioner.org.uk
    secretName: victimscommissioner-cert
  - hosts:
    - www.victimscommissioner.org.uk
    secretName: victimscommissioner-www-cert
  - hosts:
    - publicdefenderservice.org.uk
    secretName: publicdefenderservice-cert
  - hosts:
    - www.publicdefenderservice.org.uk
    secretName: publicdefenderservice-www-cert
  - hosts:
    - ccrc.gov.uk
    secretName: ccrc-cert
  - hosts:
    - www.ccrc.gov.uk
    secretName: ccrc-www-cert
  - hosts:
    - icrir.independent-inquiry.uk
    secretName: icrir-cert
  - hosts:
    - imb.org.uk
    secretName: imb-cert
  - hosts:
    - www.imb.org.uk
    secretName: imb-www-cert
  - hosts:
    - brookhouseinquiry.org.uk
    secretName: brookhouse-cert
  - hosts:
    - www.brookhouseinquiry.org.uk
    secretName: brookhouse-www-cert
  - hosts:
    - prisonandprobationjobs.gov.uk
    secretName: ppj-cert
  - hosts:
    - www.prisonandprobationjobs.gov.uk
    secretName: ppj-www-cert
  - hosts:
    - nationalpreventivemechanism.org.uk
    secretName: nationalpreventivemechanism-cert
  - hosts:
    - www.nationalpreventivemechanism.org.uk
    secretName: nationalpreventivemechanism-www-cert
  - hosts:
    - lawcom.gov.uk
    secretName: lawcom-cert
  - hosts:
    - www.lawcom.gov.uk
    secretName: lawcom-www-cert
  - hosts:
    - jobs.justice.gov.uk
    secretName: justicejobs-cert
  - hosts:
    - www.jobs.justice.gov.uk
    secretName: justicejobs-www-cert
  - hosts:
    - ppo.gov.uk
    secretName: ppo-cert
  - hosts:
    - www.ppo.gov.uk
    secretName: ppo-www-cert
  - hosts:
    - sifocc.org
    secretName: sifocc-cert
  - hosts:
    - www.sifocc.org
    secretName: sifocc-www-cert
    {{- end }}
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: wordpress
            port:
              number: 8080
  {{- if eq .Values.configmap.envtype "prod" }}
  - host: magistrates.judiciary.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: wordpress
            port:
              number: 8080
  - host: victimscommissioner.org.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: wordpress
            port:
              number: 8080
  - host: www.victimscommissioner.org.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: wordpress
            port:
              number: 8080
  - host: publicdefenderservice.org.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: wordpress
            port:
              number: 8080
  - host: www.publicdefenderservice.org.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: wordpress
            port:
              number: 8080
  - host: ccrc.gov.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: wordpress
            port:
              number: 8080
  - host: www.ccrc.gov.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: wordpress
            port:
              number: 8080
  - host: icrir.independent-inquiry.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: wordpress
            port:
              number: 8080
  - host: imb.org.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: wordpress
            port:
              number: 8080
  - host: www.imb.org.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: wordpress
            port:
              number: 8080
  - host: brookhouseinquiry.org.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: wordpress
            port:
              number: 8080
  - host: www.brookhouseinquiry.org.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: wordpress
            port:
              number: 8080
  - host: prisonandprobationjobs.gov.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: wordpress
            port:
              number: 8080
  - host: www.prisonandprobationjobs.gov.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: wordpress
            port:
              number: 8080
  - host: nationalpreventivemechanism.org.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: wordpress
            port:
              number: 8080
  - host: www.nationalpreventivemechanism.org.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: wordpress
            port:
              number: 8080
  - host: lawcom.gov.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: wordpress
            port:
              number: 8080
  - host: www.lawcom.gov.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: wordpress
            port:
              number: 8080
  - host: jobs.justice.gov.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: wordpress
            port:
              number: 8080
  - host: www.jobs.justice.gov.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: wordpress
            port:
              number: 8080
  - host: ppo.gov.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: wordpress
            port:
              number: 8080
  - host: www.ppo.gov.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: wordpress
            port:
              number: 8080
  - host: sifocc.org
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: wordpress
            port:
              number: 8080
  - host: www.sifocc.org
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: wordpress
            port:
              number: 8080
   {{- end }}
{{- end }}
