{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hale-platform-ingress
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: {{ .Values.ingress.metadata.annotations.setidentifier }} 
    external-dns.alpha.kubernetes.io/aws-weight: "100"
spec:
  ingressClassName: nginx 
  tls:
  - hosts:
    - {{ .Values.domain }} 
  rules:
  - host: {{ .Values.domain }} 
    http:
      paths:
      - path: /
        pathType: Prefix 
        backend:
          service:
            name: nginx 
            port:
              number: 8080 
{{- end }}
