{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata: 
  name: {{ .Release.Revision }}-wpsecrets 
type: Opaque
data:
  WORDPRESS_DB_USER: {{ .Value.secrets.wordpress-db-user }}
  WORDPRESS_DB_HOST: {{ .Value.secrets.wordpress-db-host }}
  WORDPRESS_DB_NAME: {{ .Value.secrets.wordpress-db-name }}
  WORDPRESS_DB_PASSWORD: {{ .Value.secrets.wordpress-db-password }}
  WORDPRESS_ADMIN_EMAIL: {{ .Value.secrets.wordpress-admin-email }}
  WORDPRESS_ADMIN_USER: {{ .Value.secrets.wordpress-admin-user }}
  WORDPRESS_ADMIN_PASSWORD: {{ .Value.secrets.wordpress-admin-password }}
  SERVICE_NAME: {{ .Value.secrets.service-name }}
  SERVICE_TAGS: {{ .Value.secrets.service-tag }}
  {{- end }}
