{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata: 
  name: {{ .Release.Revision }}-wpsecrets 
type: Opaque
data:
  WORDPRESS_DB_USER: {{ .Value.secrets.wpdbuser }}
  WORDPRESS_DB_HOST: {{ .Value.secrets.wpdbhost }}
  WORDPRESS_DB_NAME: {{ .Value.secrets.wpdbname }}
  WORDPRESS_DB_PASSWORD: {{ .Value.secrets.wpdbpassword }}
  WORDPRESS_ADMIN_EMAIL: {{ .Value.secrets.wpadminemail }}
  WORDPRESS_ADMIN_USER: {{ .Value.secrets.wpadminuser }}
  WORDPRESS_ADMIN_PASSWORD: {{ .Value.secrets.wpadminpassword }}
  SERVICE_NAME: {{ .Value.secrets.servicename }}
  SERVICE_TAGS: {{ .Value.secrets.servicetag }}
  {{- end }}
