{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata: 
  name: wpsecrets-{{ .Release.Revision }} 
type: Opaque
stringData:
  WORDPRESS_DB_USER: {{ .Values.secrets.wpdbuser }}
  WORDPRESS_DB_HOST: {{ .Values.secrets.wpdbhost }}
  WORDPRESS_DB_NAME: {{ .Values.secrets.wpdbname }}
  WORDPRESS_DB_PASSWORD: {{ .Values.secrets.wpdbpassword }}
  WORDPRESS_ADMIN_EMAIL: {{ .Values.secrets.wpadminemail }}
  WORDPRESS_ADMIN_USER: {{ .Values.secrets.wpadminuser }}
  WORDPRESS_ADMIN_PASSWORD: {{ .Values.secrets.wpadminpassword }}
{{- end }}
