{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata: 
  name: wpsecrets-{{ .Release.Revision }} 
type: Opaque
stringData:
  WORDPRESS_DB_USER: {{ .Values.secrets.wpdbuser }}
  WORDPRESS_DB_HOST: {{ .Values.secrets.wpdbhost }}
  WORDPRESS_DB_NAME: {{ .Values.secrets.wpdbname }}
  WORDPRESS_DB_PASSWORD: {{ .Values.secrets.wpdbpassword }}
  WORDPRESS_ADMIN_EMAIL: {{ .Values.secrets.wpadminemail }}
  WORDPRESS_ADMIN_USER: {{ .Values.secrets.wpadminuser }}
  WORDPRESS_ADMIN_PASSWORD: {{ .Values.secrets.wpadminpassword }}
  WORDPRESS_AUTH_KEY_FILE: {{ .Values.secrets.wpauthkeyfile }}
  WORDPRESS_AUTH_SALT_FILE: {{ .Values.secrets.wpauthsaltfile }}
  WORDPRESS_LOGGED_IN_KEY_FILE: {{ .Values.secrets.wploggedinkeyfile }}
  WORDPRESS_LOGGED_IN_SALT_FILE: {{ .Values.secrets.wploggedinsaltfile }}
  WORDPRESS_NONCE_KEY_FILE: {{ .Values.secrets.wpnoncekeyfile }}
  WORDPRESS_NONCE_SALT_FILE: {{ .Values.secrets.wpnoncesaltfile }}
  WORDPRESS_SECURE_AUTH_KEY_FILE: {{ .Values.secrets.wpsecureauthkeyfile }}
  WORDPRESS_SECURE_AUTH_SALT_FILE: {{ .Values.secrets.wpsecureauthsaltfile }}
{{- end }}
