{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata: 
  name: hale-wp-secrets-{{ .Release.Revision }} 
type: Opaque
stringData:
  WORDPRESS_DB_USER: {{ .Values.secrets.wpdbuser }}
  WORDPRESS_DB_HOST: {{ .Values.secrets.wpdbhost }}
  WORDPRESS_DB_NAME: {{ .Values.secrets.wpdbname }}
  WORDPRESS_DB_PASSWORD: {{ .Values.secrets.wpdbpassword }}
  WORDPRESS_ADMIN_EMAIL: {{ .Values.secrets.wpadminemail }}
  WORDPRESS_ADMIN_USER: {{ .Values.secrets.wpadminuser }}
  WORDPRESS_ADMIN_PASSWORD: {{ .Values.secrets.wpadminpassword }}
  WORDPRESS_AUTH_KEY: {{ .Values.secrets.wpauthkey | b64dec | quote }}
  WORDPRESS_AUTH_SALT: {{ .Values.secrets.wpauthsalt | b64dec | quote }}
  WORDPRESS_LOGGED_IN_KEY: {{ .Values.secrets.wploggedinkey | b64dec | quote }}
  WORDPRESS_LOGGED_IN_SALT: {{ .Values.secrets.wploggedinsalt | b64dec | quote }}
  WORDPRESS_NONCE_KEY: {{ .Values.secrets.wpnoncekey | b64dec | quote }}
  WORDPRESS_NONCE_SALT: {{ .Values.secrets.wpnoncesalt | b64dec | quote }}
  WORDPRESS_SECURE_AUTH_KEY: {{ .Values.secrets.wpsecureauthkey | b64dec | quote }}
  WORDPRESS_SECURE_AUTH_SALT: {{ .Values.secrets.wpsecureauthsalt | b64dec | quote }}
  S3_UPLOADS_BUCKET:  {{ .Values.secrets.s3uploadsbucket }}
  S3_UPLOADS_REGION: {{ .Values.secrets.s3uploadsregion }}
{{- end }}
