---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: {{ .Values.namespace }}
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "443"
      port: 443
      targetPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: {{ .Values.namespace }} 
  labels:
    app: mariadb
spec:
  ports:
  - port: 3306
  selector:
    app: mariadb
    tier: frontend-c
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: {{ .Values.namespace }} 
  labels:
    app: wordpress
spec:
  ports:
    - name: "9000"
      port: 9000
  selector:
    app: wordpress
    tier: frontend-c
