{{- if .Values.mariadb.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  ports:
  - port: 3306
  selector:
    app: mariadb
    tier: frontend-c
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - name: "8080"
      port: 8080
    - name: "443"
      port: 443
  selector:
    app: wordpress
    tier: frontend-c
