apiVersion: batch/v1
kind: CronJob
metadata:
  name: wp-cron 
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          containers:
          - name: busybox-curl
            image: joeshaw/busybox-nonroot 
            args:
            - curl
            - https://hale-platform-dev.apps.live.cloud-platform.service.justice.gov.uk/wp-cron-multisite.php
          restartPolicy: OnFailure
