apiVersion: batch/v1
kind: CronJob
metadata:
  name: wp-cron
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          containers:
          - name: nginx-curl
            image: nginxinc/nginx-unprivileged
            args:
            - curl
            - {{ .Values.domain }}/wp-cron-multisite.php
          restartPolicy: OnFailure
          imagePullPolicy: IfNotPresent