# Default values for wordpress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

domain: hale.docker

# nginx
nginx:
  image:
    repository: hale-platform-nginx
    pullPolicy: IfNotPresent

# wordpress 
image:
  repository: hale-platform-wordpress
  pullPolicy: IfNotPresent

mariadb:
  enabled: true

ingress:
  enabled: false
