# Default values for wordpress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Empty strings mean value is overwritten and populated when run by GitAction
# during deployment

domain: "" 

nginx:
  image:
    repository: "" 
    pullPolicy: IfNotPresent
    replicaCount: 3
 
wp:
  image:
    repository: "" 
    pullPolicy: IfNotPresent
    replicaCount: 1 

mariadb:
  enabled: false

ingress:
  enabled: true

configmap:
  wpenvtype: ""
  servername: ""

secrets:
  enabled: true
  wpdbuser: ""
  wpdbhost: ""
  wpdbname: ""
  wpdbpassword: ""
  wpadminemail: ""
  wpadminuser: ""
  wpadminpassword: ""
