# Default values for wordpress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

domain: hale-platform-dev.apps.live.cloud-platform.service.justice.gov.uk

# Empty strings likely mean value is overwritten when run by GitAction
# during deployment

nginx:
  image:
    repository: "" 
    pullPolicy: IfNotPresent
    replicaCount: 3
 
wp:
  image:
    repository: "" 
    pullPolicy: IfNotPresent
    replicaCount: 3

mariadb:
  enabled: false

ingress:
  enabled: true
