# Default values for wordpress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

domain: hale-platform-dev.apps.live.cloud-platform.service.justice.gov.uk

# nginx
nginx:
  image:
    repository: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/jotw-content-devs/hale-platform-dev-ecr:hale-platform_nginx
    pullPolicy: IfNotPresent

# wordpress 
image:
  repository: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/jotw-content-devs/hale-platform-dev-ecr:hale-platform_wordpress
  pullPolicy: IfNotPresent

mariadb:
  enabled: false

ingress:
  enabled: true
