# Default values for wordpress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Empty strings mean value is overwritten and populated when run by GitAction
# during deployment

domain: ""

nginx:
  image:
    repository: ""
    imagePullPolicy: Always

wp:
  image:
    repository: ""
    imagePullPolicy: Always

    # Default if HPA is not turned on
    replicaCount:
      prod: 3
      staging: 2
      dev: 1
      demo: 2

hpa:
  enabled: true

cron:
  feedparser:
    enabled: true

ingress:
  enabled: true
  metadata:
    annotations:
      setidentifier: ""
  hosts:
    - name: magistrates.judiciary.uk
      certName: magistrates-cert
    - name: victimscommissioner.org.uk
      certName: victimscommissioner-cert
    - name: www.victimscommissioner.org.uk
      certName: victimscommissioner-www-cert
    - name: publicdefenderservice.org.uk
      certName: publicdefenderservice-cert
    - name: www.publicdefenderservice.org.uk
      certName: publicdefenderservice-www-cert
    - name: ccrc.gov.uk
      certName: ccrc-cert
    - name: www.ccrc.gov.uk
      certName: ccrc-www-cert
    - name: icrir.independent-inquiry.uk
      certName: icrir-cert
    - name: intranet.icrir.independent-inquiry.uk
      certName: icrir-intranet-cert
    - name: imb.org.uk
      certName: imb-cert
    - name: www.imb.org.uk
      certName: imb-www-cert
    - name: my.imb.org.uk
      certName: my-imb-cert
    - name: brookhouseinquiry.org.uk
      certName: brookhouse-cert
    - name: www.brookhouseinquiry.org.uk
      certName: brookhouse-www-cert
    - name: prisonandprobationjobs.gov.uk
      certName: ppj-cert
    - name: www.prisonandprobationjobs.gov.uk
      certName: ppj-www-cert
    - name: nationalpreventivemechanism.org.uk
      certName: nationalpreventivemechanism-cert
    - name: www.nationalpreventivemechanism.org.uk
      certName: nationalpreventivemechanism-www-cert
    - name: lawcom.gov.uk
      certName: lawcom-cert
    - name: www.lawcom.gov.uk
      certName: lawcom-www-cert
    - name: jobs.justice.gov.uk
      certName: justicejobs-cert
    - name: www.jobs.justice.gov.uk
      certName: justicejobs-www-cert
    - name: ppo.gov.uk
      certName: ppo-cert
    - name: www.ppo.gov.uk
      certName: ppo-www-cert
    - name: archive.ppo.gov.uk
      certName: ppo-archive-cert
    - name: sifocc.org
      certName: sifocc-cert
    - name: www.sifocc.org
      certName: sifocc-www-cert
    - name: layobservers.org
      certName: layobservers-cert
    - name: www.layobservers.org
      certName: layobservers-www-cert
    - name: members.layobservers.org
      certName: layobservers-members-cert
    - name: victimandwitnessinformation.org.uk
      certName: victimandwitnessinformation-cert
    - name: www.victimandwitnessinformation.org.uk
      certName: victimandwitnessinformation-www-cert
    - name: cym.victimandwitnessinformation.org.uk
      certName: victimandwitnessinformation-cym-cert
    - name: victimscode.org.uk
      certName: victimscode-cert
    - name: cym.victimscode.org.uk
      certName: victimscode-cym-cert
    - name: omagh.independent-inquiry.uk
      certName: obi-cert
    - name: www.omagh.independent-inquiry.uk
      certName: obi-www-cert
    - name: newfuturesnetwork.gov.uk
      certName: newfuturesnetwork-cert
    - name: www.newfuturesnetwork.gov.uk
      certName: newfuturesnetwork-www-cert
    - name: andrewmalkinson.independent-inquiry.uk
      certName: andrewmalkinson-cert
    - name: www.andrewmalkinson.independent-inquiry.uk
      certName: andrewmalkinson-www-cert
    - name: hmiprisons.justiceinspectorates.gov.uk
      certName: justiceinspectorates-hmiprisons-cert
    - name: showcase.websitebuilder.service.justice.gov.uk
      certName: websitebuilder-showcase-cert

configmap:
  servername: ""
  envtype: ""
  s3useprofile: "true"
  sentrydns: ""

secrets:
  enabled: true
  wpdbuser: ""
  wpdbhost: ""
  wpdbname: ""
  wpdbpassword: ""
  wpadminemail: ""
  wpadminuser: ""
  wpadminpassword: ""
  wpauthkey: ""
  wpauthsalt: ""
  wploggedinkey: ""
  wploggedinsalt: ""
  wpnoncekey: ""
  wpnoncesalt: ""
  wpsecureauthkey: ""
  wpsecureauthsalt: ""
  s3uploadsbucket: ""
  s3uploadsregion: ""
  feedparser:
    avatureFeedUserName: ""
    avatureFeedUserPassword: ""

alertSecrets:
  enabled: true
  slackWebhookUrl: ""
  
