# Default values for wordpress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Empty strings mean value is overwritten and populated when run by GitAction
# during deployment

domain: ""

nginx:
  image:
    repository: ""
    imagePullPolicy: Always

wp:
  image:
    repository: ""
    imagePullPolicy: Always
    replicaCount:
      prod: 3
      staging: 3
      dev: 1
      demo: 2

mariadb:
  enabled: false

ingress:
  enabled: true
  metadata:
    annotations:
      setidentifier: ""

configmap:
  servername: ""
  envtype: ""
  # wpdebug:
  #   prod: false
  #   staging: true
  #   dev: true
  #   demo: true

secrets:
  enabled: true
  wpdbuser: ""
  wpdbhost: ""
  wpdbname: ""
  wpdbpassword: ""
  wpadminemail: ""
  wpadminuser: ""
  wpadminpassword: ""
  wpauthkey: ""
  wpauthsalt: ""
  wploggedinkey: ""
  wploggedinsalt: ""
  wpnoncekey: ""
  wpnoncesalt: ""
  wpsecureauthkey: ""
  wpsecureauthsalt: ""
  s3uploadsbucket: ""
  s3uploadsregion: ""
  s3uploadskey: ""
  s3uploadssecret: ""

alert-secrets:
  slackwebhookurl: ""