---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
      tier: frontend-c
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
        tier: frontend-c
    spec:
      containers:
      - name: mysql  
        image: mariadb:10.7.1-focal
        envFrom:
          - configMapRef:
              name: wpconfig
        ports:
          - containerPort: 3306
            name: mysql
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/li/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: pvc-mysql 
