# .github/workflows/branch-protection.yml
name: Branch Protection
on:
  pull_request:
    branches: [ main ]

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Block dev and demo branches
        if: github.head_ref == 'dev' || github.head_ref == 'demo'
        run: |
          echo "❌ Direct merges from dev and demo branches to main are not allowed"
          echo "Please create a feature branch from main or use staging branch"
          exit 1
      
      - name: Allow merge
        if: github.head_ref != 'dev' && github.head_ref != 'demo'
        run: echo "✅ Branch merge is allowed"
