name: New Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'
      - 'demo'
jobs:

  setenv:
    name: Set Environment
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      deployenv: ${{ steps.outputEnv.outputs.deployenv }}
    steps:
      - id: stepDev
        if: github.event.ref == 'refs/heads/dev'
        run: |
          echo "DEPLOYENV=Development" >> $GITHUB_ENV
      - id: stepDemo
        if: github.event.ref == 'refs/heads/demo'
        run: echo "DEPLOYENV=Demonstration" >> $GITHUB_ENV
      - id: outputEnv
        run: |
          echo Deploying to $DEPLOYENV
          echo "deployenv=$DEPLOYENV" >> "$GITHUB_OUTPUT"
          
  deployDev:
    name: Deploy to Dev
    needs: setenv
    environment: ${{needs.setenv.outputs.deployenv}}