name: New Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'


jobs:

  setenv:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      deployenv: ${{ steps.outputEnv.outputs.deployenv }}
    steps:
      - id: stepDev
        if: github.event.ref == 'refs/heads/dev'
        run: echo "DEPLOYENV=Development" >> $GITHUB_ENV
      - id: outputEnv
        run: |
          echo Deploying to $DEPLOYENV
          echo "deployenv=$DEPLOYENV" >> "$GITHUB_OUTPUT"

  testjob:
    name: Test Job
    runs-on: ubuntu-latest
    needs: setenv
    environment: ${{needs.setenv.outputs.deployenv}}
    steps:
      - name: Output Vars 
        run: |
          echo "${{ vars.EXAMPLEVAR1 }}" 
     
  buildImageAndPush:
      name: Build Image and push to ECR
      runs-on: ubuntu-latest
      needs: setenv
      environment: ${{needs.setenv.outputs.deployenv}}
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Build NGINX image
          run: |
            docker build --pull --no-cache --tag hale-platform_nginx --file nginx.dockerfile .
        - name: Push NGINX image to ECR
          uses: jwalton/gh-ecr-push@v1
          with:
            access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID_DEV }}
            secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY_DEV }}
            region: eu-west-2
            local-image: hale-platform_nginx
            image: ${{ secrets.ECR_NAME_DEV }}:hale-platform_nginx-${{ github.sha }}
        - name: Run Composer
          run: |
            composer config http-basic.composer.wp.dsd.io ${{ secrets.COMPOSER_USER }} ${{ secrets.COMPOSER_PASS }}
            composer install --prefer-dist --no-progress
        - name: Run NPM
          run: |
            npm install --prefix ./wordpress/wp-content/themes/hale
            npm run production --if-present --prefix ./wordpress/wp-content/themes/hale
        - name: Build WordPress image
          run: |
            docker build --pull --no-cache --tag hale-platform_wordpress --file wp.dockerfile .
        - name: Push WordPress image to ECR
          uses: jwalton/gh-ecr-push@v1
          with:
            access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID_DEV }}
            secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY_DEV }}
            region: eu-west-2
            local-image: hale-platform_wordpress:latest
            image: ${{ secrets.ECR_NAME_DEV }}:hale-platform_wordpress-${{ github.sha }}