name: New Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'
      - 'demo'
jobs:

  setenv:
    name: Set Environment
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      deployenv: ${{ steps.outputEnv.outputs.deployenv }}
    steps:
      - id: stepDev
        if: github.event.ref == 'refs/heads/dev'
        run: |
          echo "DEPLOYENV=Development" >> $GITHUB_ENV
      - id: stepDemo
        if: github.event.ref == 'refs/heads/demo'
        run: echo "DEPLOYENV=Demonstration" >> $GITHUB_ENV
      - id: outputEnv
        run: |
          echo Deploying to $DEPLOYENV
          echo "deployenv=$DEPLOYENV" >> "$GITHUB_OUTPUT"
          
  deployDev:
      name: Deploy to Dev
      needs: setenv
      environment: ${{needs.setenv.outputs.deployenv}}
      uses: ./.github/workflows/rw-build-image.yaml
      with:
        deploy-env: ${{needs.setenv.outputs.deployenv}}
        env-type: Dev
      secrets:
        ecr-name: ${{ secrets.ECR_NAME }}
        ecr-role: ${{ secrets.DEV_ECR_ROLE_TO_ASSUME }}
        ecr-region: ${{ vars.DEV_ECR_REGION }}
        ecr-repo: ${{ vars.DEV_ECR_REPOSITORY }} 
        cp-user: ${{ secrets.COMPOSER_USER }}
        cp-password: ${{ secrets.COMPOSER_PASS }}
        kube-cluster: ${{ secrets.KUBE_CLUSTER }}
        kube-cert: ${{ secrets.KUBE_CERT }}
        kube-namespace: ${{ secrets.KUBE_NAMESPACE }}
        kube-token: ${{ secrets.KUBE_TOKEN }}
        wp-db-user: ${{ secrets.WORDPRESS_DB_USER }}
        wp-db-host: ${{ secrets.WORDPRESS_DB_HOST }}
        wp-db-name: ${{ secrets.WORDPRESS_DB_NAME }}
        wp-db-password: ${{ secrets.WORDPRESS_DB_PASSWORD }}
        wp-admin-email: ${{ secrets.WORDPRESS_ADMIN_EMAIL }}
        wp-admin-user: ${{ secrets.WORDPRESS_ADMIN_USER }}
        wp-admin-password: ${{ secrets.WORDPRESS_ADMIN_PASSWORD }}
        wp-auth-key-file: ${{ secrets.WORDPRESS_AUTH_KEY_FILE }}
        wp-auth-salt-file: ${{ secrets.WORDPRESS_AUTH_SALT_FILE }}
        wp-loggedin-key-file: ${{ secrets.WORDPRESS_LOGGED_IN_KEY_FILE }}
        wp-loggedin-salt-file: ${{ secrets.WORDPRESS_LOGGED_IN_SALT_FILE }}
        wp-nonce-key-file: ${{ secrets.WORDPRESS_NONCE_KEY_FILE }}
        wp-nonce-salt-file: ${{ secrets.WORDPRESS_NONCE_SALT_FILE }}
        wp-secure-auth-key-file: ${{ secrets.WORDPRESS_SECURE_AUTH_KEY_FILE }}
        wp-secure-auth-salt-file: ${{ secrets.WORDPRESS_SECURE_AUTH_SALT_FILE }}
        s3-uploads-bucket: ${{ secrets.S3_UPLOADS_BUCKET }}
        s3-uploads-region: ${{ secrets.S3_UPLOADS_REGION }}   
        alert-slack-webhook-url: ${{ secrets.ALERT_SLACK_WEBHOOK_URL }} 
      
