name: New Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'


jobs:
  buildImage:
      name: Build Image and push to ECR
      runs-on: ubuntu-latest
      environment: Development
      permissions:
        id-token: write # This is required for requesting the JWT
        contents: read  # This is required for actions/checkout
      steps:
      # Checkout GitHub repository
        - uses: actions/checkout@v3

        # Assume role in Cloud Platform
        - uses: aws-actions/configure-aws-credentials@v2
          with:
            role-to-assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}
            aws-region: ${{ vars.ECR_REGION }}

        # Login to container repository
        - uses: aws-actions/amazon-ecr-login@v1
          id: login-ecr