name: Rob Test Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - 'robdev'
      - 'robdemo'


jobs:

  setenv:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      deployenv: ${{ steps.outputEnv.outputs.deployenv }}
    steps:
      - id: stepDev
        if: github.event.ref == 'refs/heads/robdev'
        run: echo "DEPLOYENV=RobDev" >> $GITHUB_ENV
      - id: stepDemo
        if: github.event.ref == 'refs/heads/robdemo'
        run: echo "DEPLOYENV=RobDemo" >> $GITHUB_ENV
      - id: outputEnv
        run: |
          echo $DEPLOYENV
          echo "deployenv=$DEPLOYENV" >> "$GITHUB_OUTPUT"

  testjob:
    name: Test Job
    runs-on: ubuntu-latest
    needs: setenv
    environment: ${{needs.setenv.outputs.deployenv}}
    steps:
      - name: Output Vars
        run: |
          echo "${{ vars.EXAMPLEVAR1 }}" 
          echo "${{ vars.EXAMPLEVAR2 }}" 